/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calcprog_1(char *host, double num1, char op, double num2)
{
	CLIENT *clnt;
	double * result;

//	double  *result_1;
//	double suma_1_arg1;
//	double suma_1_arg2;
//	double  *result_2;
//	double resta_1_arg1;
//	double resta_1_arg2;
//	double  *result_3;
//	double mul_1_arg1;
//	double mul_1_arg2;
//	double  *result_4;
//	double div_1_arg1;
//	double div_1_arg2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCPROG, CALCVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(op){
		case '+':
			printf("1\n");
			result = suma_1(num1,num2,clnt);
			printf("Resultado: %f\n", *result);
			break;
		case '-':
			printf("2\n");
			result=resta_1(num1,num2,clnt);
			printf("Resultado: %f\n", *result);
			break;
		case 'x':
			printf("3\n");
			result=mul_1(num1,num2,clnt);
			printf("Resultado: %f\n", *result);
			break;
		case '/':
			printf("4\n");
			result=div_1(num1,num2,clnt);
			printf("Resultado: %f\n",*result);
			break;	
		default:
			printf("Operador erroneo\n");		
			break;	
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc != 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	double num1 = atoi(argv[2]);
	char op = (char)argv[3][0];
	double num2 = atoi(argv[4]);
	calcprog_1 (host, num1, op, num2);


exit (0);
}
