/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DNS1_H_RPCGEN
#define _DNS1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct registrar_1_argument {
	char *arg1;
	char *arg2;
};
typedef struct registrar_1_argument registrar_1_argument;

#define DNS1 0x20000001
#define DNS2 0x20000002
#define DNSVER1 1
#define DNSVER2 2

#if defined(__STDC__) || defined(__cplusplus)
#define registrar 1
extern  void * registrar_1(char *, char *, CLIENT *);
extern  void * registrar_1_svc(char *, char *, struct svc_req *);
#define borrar 2
extern  void * borrar_1(char *, CLIENT *);
extern  void * borrar_1_svc(char *, struct svc_req *);
#define buscar 3
extern  char ** buscar_1(char *, CLIENT *);
extern  char ** buscar_1_svc(char *, struct svc_req *);
#define cliente 4
extern  char ** cliente_1(char *, CLIENT *);
extern  char ** cliente_1_svc(char *, struct svc_req *);
extern int dns1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrar 1
extern  void * registrar_1();
extern  void * registrar_1_svc();
#define borrar 2
extern  void * borrar_1();
extern  void * borrar_1_svc();
#define buscar 3
extern  char ** buscar_1();
extern  char ** buscar_1_svc();
#define cliente 4
extern  char ** cliente_1();
extern  char ** cliente_1_svc();
extern int dns1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registrar_1_argument (XDR *, registrar_1_argument*);

#else /* K&R C */
extern bool_t xdr_registrar_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DNS1_H_RPCGEN */
