/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns2.h"
#include <map>
#include <iostream>

using namespace std;



void *
registrar_1_svc(char *arg1, char *arg2,  struct svc_req *rqstp)
{
	static char * result;

	string a=arg1, b=arg2;
	dns[a]=b;

	return (void *) &result;
}

void *
borrar_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;

	string a=arg1;
	map<string,string>::iterator it;
	it=dns.find(a);
	dns.erase(it)

	return (void *) &result;
}

char **
buscar_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;

	string a=arg1;
	result=dns[a].c_str();

	return &result;
}
